// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseRepository
{
    public partial class Gender
    {
        public byte Id { get; set; }
        public string Gender1 { get; set; }
    }
}