// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseRepository
{
    public partial class PersonOrganizations
    {
        public Guid PersonId { get; set; }
        public Guid OrganizationId { get; set; }

        public virtual Organizations Organization { get; set; }
        public virtual Persons Person { get; set; }
    }
}