// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseRepository
{
    public partial class Persons
    {
        public Persons()
        {
            PersonOrganizations = new HashSet<PersonOrganizations>();
        }

        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte GenderId { get; set; }
        public string PersonalNumber { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<PersonOrganizations> PersonOrganizations { get; set; }
    }
}